[package]
name = "tomato"
version = "0.1.0"
edition = "2021"
description = "cli pomodoro timer"
homepage = "https://github.com/kironono/tomato"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.16.2"
